# Generated by Django 3.1.1 on 2020-09-22 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200921_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicesresponse',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choices_responses', to='polls.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.poll'),
        ),
        migrations.AlterField(
            model_name='singlechoiceresponse',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice_responses', to='polls.choice'),
        ),
        migrations.AlterField(
            model_name='textresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_responses', to='polls.question'),
        ),
        migrations.AddConstraint(
            model_name='singlechoiceresponse',
            constraint=models.UniqueConstraint(fields=('user', 'choice'), name='single_choice_responce_user_choice_constraint'),
        ),
    ]
