# Generated by Django 3.1.1 on 2020-09-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200928_0605'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choice',
            name='choice__question_text__unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'text'), name='choice__question__text__unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('poll', 'text'), name='question__poll__text__unique_constraint'),
        ),
    ]
