# Generated by Django 3.1.1 on 2020-09-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200928_0631'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='singlechoiceresponse',
            name='single_choice_responce__user__question__unique_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='singlechoiceresponse',
            name='single_choice_responce__user__choice__unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='singlechoiceresponse',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='single_choice_response__user__question__unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='singlechoiceresponse',
            constraint=models.UniqueConstraint(fields=('user', 'choice'), name='single_choice_response__user__choice__unique_constraint'),
        ),
    ]
