# Generated by Django 3.1.1 on 2020-10-01 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200928_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Key'),
        ),
    ]
