# Generated by Django 3.1.1 on 2020-10-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous_auth', '0001_initial'),
        ('polls', '0012_auto_20201001_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicesresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_auth.user'),
        ),
        migrations.AlterField(
            model_name='singlechoiceresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_auth.user'),
        ),
        migrations.AlterField(
            model_name='textresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonymous_auth.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
